AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: npb-notify
Parameters:
  TagName:
    Type: String
  WebhookUrlSlack:
    Type: String
  BaseDomainName:
    Type: String
    NoEcho: true
Resources:
  NpbNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub npb-notify-${TagName}
      PackageType: Zip
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 512
      Timeout: 900
      Architectures:
        - arm64
      Environment:
        Variables:
          NPB_BASE_DOMAIN_NAME: !Ref BaseDomainName
          WEBHOOK_URL: !Ref WebhookUrlSlack
          INTERVAL_SECONDS: 1.5
          IS_DEVELOPMENT: false
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            Name: !Sub npb-notify-schedule-${TagName}
            ScheduleExpression: cron(45 13,17 * * ? *)
            ScheduleExpressionTimezone: Asia/Tokyo
